### ISSUE TITLE
!!single_sign

### ISSUE THREAD

**Issue by gsmithufl** [iotaledger/ledger-iota-app#12]
I haven't seen this structure before, I'm assuming its not not, which would be single_sign?

https://github.com/iotaledger/ledger-iota-app/blob/7ab9a796421a5906ada80a786e40d6cc27082188/src/api.c#L363

**Comment by shufps** [comment]
@gsmithufl no, `!!` restricts the value to `0` and `1`. For instance `!!5` would become `1`.

Without using `!!` it would like like `api.essence.single_sign_mode = (single_sign) ? 1 : 0;`.
