### ISSUE TITLE
Feature Request: Change/Remainder to same address (configurable)

### ISSUE THREAD

**Issue by Skerberus** [iotaledger/ledger-iota-app#18]
"Change/Remainder: After sending funds to a 3rd party, all remaining funds on the account must be transferred to a new address - this is called the change or remainder address."

Currently whenever I send IOTA using the ledger the remainder is stored on a new address. Since chrysalis this is not mandatory anymore. It would be nice to have the option to keep the remainder on the current address. This could be e.g. useful for tax reasons where you want to show hat you hold IOTA for a given time without proving that you own every address that was generated during sending of iota.

**Comment by shufps** [comment]
Hi, this is not a Nano Ledger app issue - probably you should open an issue in Firefly :thinking: The Ledger Nano app only _consumes_ what is sent to the app by firefly or cli-wallet.
