### ISSUE TITLE
Private key management: exception handling

### ISSUE THREAD

**Issue by yhql** [iotaledger/ledger-iota-app#4]
Hello, this is part of a security review of your application (and is the only potential problem found :) ).

There are 2 functions that call `cx_...` SDK functions that can throw without a `CATCH {}` around that would cleanup sensitive data like the private key.

- https://github.com/iotaledger/ledger-iota-app/blob/develop/src/iota/ed25519.c#L28-L42 control flow can exit with a THROW in `cx_ecfp_generate_pair` and leave `keySeed` filled.
- https://github.com/iotaledger/ledger-iota-app/blob/develop/src/iota/essence.c#L458-L477 control flow can exit with a THROW in `ed25519_sign`

### Fixing

The related guidance for this problem is available [here](https://ledger.readthedocs.io/en/latest/additional/security_guidelines.html#private-key-management). 

One example usage is available [in the 'boilerplate' app](https://github.com/LedgerHQ/app-boilerplate/blob/master/src/crypto.c#L32-L53)

**Comment by shufps** [comment]
@yhql  fixed 🥳

Thank you very much for your review! :hugs:
